# Generated by Django 5.2.4 on 2025-08-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0003_alter_usuario_ci_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
