# Generated by Django 5.2.4 on 2025-08-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0005_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logacceso',
            name='codigo_modulo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
