# Generated by Django 5.2.4 on 2025-08-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0006_logacceso_codigo_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
