# Generated by Django 5.2.4 on 2025-08-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0007_mascota_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
