# Generated by Django 5.2.4 on 2025-08-14 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0008_vacuna_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotavacuna',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mascotavacuna',
            name='veterinario',
            field=models.ForeignKey(default=1, limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
