# Generated by Django 5.2.4 on 2025-08-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0009_mascotavacuna_estado_mascotavacuna_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontratamiento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='composicionconsulta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluaciondiagnostico',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='observacionsintoma',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asistida', 'Asistida'), ('cancelada', 'Cancelada'), ('programada', 'Programada')], default='pendiente', max_length=20),
        ),
    ]
