# Generated by Django 5.2.4 on 2025-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0010_acciontratamiento_estado_cita_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intentos_sesion',
            field=models.IntegerField(default=0),
        ),
    ]
