# Generated by Django 5.2.4 on 2025-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0012_alter_cita_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicionconsulta',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='composicionconsulta',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
