# Generated by Django 5.2.4 on 2025-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0013_composicionconsulta_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontratamiento',
            name='estado_tratamiento',
            field=models.CharField(choices=[('en curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
