# Generated by Django 5.2.4 on 2025-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0014_acciontratamiento_estado_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='dosis',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='medicamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
