# Generated by Django 5.2.4 on 2025-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0015_receta_dosis_receta_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotavacuna',
            name='composicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asistida', 'Asistida'), ('cancelada', 'Cancelada'), ('programada', 'Programada'), ('no asistida', 'No Asistida')], default='pendiente', max_length=20),
        ),
    ]
