# Generated by Django 5.2.4 on 2025-09-23 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0016_mascotavacuna_composicion_alter_cita_estado_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicionconsulta',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
